spring:
  application:
    name: srv.iidm.transformer
server:
  port: ${IIDM_TRANSFORMER_PORT:8098}
iidm:
  transform:
    raw-bucket: cnm-rdf-models
    event:
      exchange: iidm.events
      dead-letter-exchange: iidm.events.dlx
      requested-routing-key: iidm.profile.transform.requested
      requested-queue: iidm.profile.transform
      requested-dlq: iidm.profile.transform.dlq
      requested-dead-letter-routing-key: iidm.profile.transform.failed.dlq
      started-routing-key: iidm.profile.transform.started
      completed-routing-key: iidm.profile.transform.completed
      failed-routing-key: iidm.profile.transform.failed
  grid-view:
    bucket: ${IIDM_GRID_VIEW_BUCKET:iidm-grid-view}
    output-format: svg
    use-geographical-positions: true
springdoc:
  swagger-ui:
    url: /openapi/iidm-transformer.yaml
