spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/egm
          jwk-set-uri: http://localhost:8081/realms/egm/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/egm
        registration:
          keycloak-admin:
            provider: keycloak
            client-id: egm-auth-admin
            client-secret: change-me
            authorization-grant-type: client_credentials
            scope: openid

auth:
  keycloak:
    base-url: http://localhost:8081
    realm: egm
    admin-client-id: egm-auth-admin
    admin-client-secret: change-me

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
