spring:
  application:
    name: com.auth

server:
  port: 8082

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    eu:
      egm: INFO
