openapi: 3.0.3
info:
  title: Mock CSA Services API
  version: 0.1.0
paths:
  /api/csa/cases:
    post:
      summary: Start a mocked CSA case
      responses:
        '200': { description: Mock CSA status }
    get:
      summary: List mocked CSA cases
      responses:
        '200': { description: Mock CSA cases }
  /api/csa/cases/{csaCaseId}:
    get:
      summary: Get mocked CSA case
      responses:
        '200': { description: Mock CSA case }
