spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
utility:
  object-storage:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:minioadmin}
    buckets: ${LFSA_OBJECT_STORAGE_BUCKETS:lfsa-inputs}
  messaging:
    listener:
      retry:
        max-attempts: ${LFSA_RABBIT_RETRY_MAX_ATTEMPTS:3}
        initial-interval-ms: ${LFSA_RABBIT_RETRY_INITIAL_INTERVAL_MS:10000}
        multiplier: ${LFSA_RABBIT_RETRY_MULTIPLIER:2.0}
        max-interval-ms: ${LFSA_RABBIT_RETRY_MAX_INTERVAL_MS:60000}
    topic-exchange:
      name: ${LFSA_EVENT_EXCHANGE:lfsa.events}
