spring:
  application:
    name: srv.common.lfsa
server:
  port: ${LFSA_SERVICES_PORT:8091}
springdoc:
  swagger-ui:
    url: /openapi/lfsa-services.yaml
lfsa:
  security-analysis:
    event:
      exchange: ${LFSA_EVENT_EXCHANGE:lfsa.events}
      dead-letter-exchange: ${LFSA_EVENT_DLX:lfsa.events.dlx}
      requested-routing-key: ${LFSA_SECURITY_ANALYSIS_REQUESTED_ROUTING_KEY:lfsa.security-analysis.requested}
      requested-queue: ${LFSA_SECURITY_ANALYSIS_REQUESTED_QUEUE:lfsa.security-analysis}
      requested-dlq: ${LFSA_SECURITY_ANALYSIS_REQUESTED_DLQ:lfsa.security-analysis.dlq}
      requested-dead-letter-routing-key: ${LFSA_SECURITY_ANALYSIS_REQUESTED_DLX_ROUTING_KEY:lfsa.security-analysis.failed.dlq}
