spring:
  application:
    name: srv.csa.services
server:
  port: ${CSA_SERVICES_PORT:8095}
csa:
  services:
    lfsa-base-url: ${LFSA_BASE_URL:http://localhost:8091}
    rao-base-url: ${RAO_BASE_URL:http://localhost:8093}
  bpm:
    remote-base-url: ${CSA_BPM_BASE_URL:http://localhost:8097}
springdoc:
  swagger-ui:
    url: /openapi/csa-services.yaml
