spring:
  application:
    name: bpm.csa.service
  datasource:
    url: jdbc:h2:mem:csa-bpm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
server:
  port: ${CSA_BPM_PORT:8097}
camunda:
  bpm:
    database:
      type: h2
    history-level: full
    admin-user:
      id: admin
      password: admin
