server {
  listen 80;
  server_name _;
  client_max_body_size 16m;
  client_body_timeout 600s;

  root /usr/share/nginx/html;
  index index.html;

  location /api/csa/ {
    resolver 127.0.0.11 ipv6=off valid=10s;
    set $csa_api srv-csa-services:8095;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
    proxy_pass http://$csa_api;
  }

  location /api/cnm/ {
    resolver 127.0.0.11 ipv6=off valid=10s;
    set $cnm_api srv-cnm-services:8080;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_request_buffering off;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
    proxy_pass http://$cnm_api;
  }

  location /api/iidm/ {
    resolver 127.0.0.11 ipv6=off valid=10s;
    set $iidm_api srv-iidm-transformer:8098;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
    proxy_pass http://$iidm_api;
  }

  location /api/common/lfsa/ {
    resolver 127.0.0.11 ipv6=off valid=10s;
    set $lfsa_api srv-common-lfsa:8091;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
    proxy_pass http://$lfsa_api;
  }

  location / {
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
    try_files $uri $uri/ /index.html;
  }
}
