spring:
  application:
    name: srv.cgm.importer
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    elasticsearch:
      repositories:
        enabled: false

management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    eu:
      egm: INFO
